apiVersion: v1
kind: Service
metadata:
  name: private-api-svc
  namespace: private
spec:
  ports:
    - targetPort: 3002 # POD port
      port: 3002 # service port
  selector: # POD labels
    app: private-api