apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy-lifecycle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifecycle

  template:
    metadata:
      name: lifecycle-pod
      labels:
        app: lifecycle
    spec:
      containers:
        - name: color
          image: docker.io/kodekloud/webapp-color:v1
          resources: {}
          envFrom:
            - configMapRef:
                name: demo-configmap
