apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-lifeness

spec:
  replicas: 1
  selector:
    matchLabels:
      test: liveness

  template:
    metadata:
      labels:
        test: liveness
      name: liveness-http
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/liveness
        resources: {}
        args:
        - /server
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-lifeness-exec

spec:
  replicas: 1
  selector:
    matchLabels:
      test: liveness-exec

  template:
    metadata:
      labels:
        test: liveness-exec
      name: liveness-exec
    spec:
      containers:
      - name: liveness
        image: k8s.gcr.io/busybox
        resources: {}
        args: # ejecuta un sleep de 30s para simular un estado de salud OK, luego envía un estado fallido.
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5