apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-api-pvc
  namespace: public

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi